runtime: nodejs20

service: default

# Environment variables
env_variables:
  NODE_ENV: production
  GOOGLE_CLOUD_PROJECT: taigaishida-217622
  GCLOUD_PROJECT: taigaishida-217622

# Instance configuration
instance_class: F1

# Health check configuration
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Skip files that aren't needed in production
skip_files:
  # Build artifacts and temporary files
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$

  # Development dependencies and source files
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.svelte-kit/.*$
  - ^(.*/)?src/.*$
  - ^(.*/)?static/.*$

  # Test files
  - ^(.*/)?tests?/.*$
  - ^(.*/)?.*\.test\..*$
  - ^(.*/)?.*\.spec\..*$

  # Version control and development config
  - ^(.*/)?\.git.*$
  - ^(.*/)?\.env.*$
  - ^(.*/)?README\.md$
  - ^(.*/)?tsconfig\.json$
  - ^(.*/)?svelte\.config\.js$
  - ^(.*/)?vite\.config\.ts$
  - ^(.*/)?eslint\.config\.js$
  - ^(.*/)?\.prettierrc$
  - ^(.*/)?\.prettierignore$
  - ^(.*/)?\.gcloudignore$

  # Lock files
  - ^(.*/)?pnpm-lock\.yaml$
  - ^(.*/)?yarn\.lock$
  - ^(.*/)?package-lock\.json$

  # Python and other development artifacts
  - ^(.*/)?\.ruff_cache/.*$
  - ^(.*/)?\.ropeproject/.*$
  - ^(.*/)?\.venv/.*$
  - ^(.*/)?__pycache__/.*$

  # IDE and OS files
  - ^(.*/)?\.vscode/.*$
  - ^(.*/)?\.idea/.*$
  - ^(.*/)?\.DS_Store$
  - ^(.*/)?Thumbs\.db$
