service: default
runtime: python310
entrypoint: python3 -m uvicorn taigaishida.taiga:app --port ${PORT}
env_variables:
  PLANETARIUM_URL: "https://planetarium-dot-taigaishida-217622.wl.r.appspot.com/static/images/"
