service: default
runtime: python311
entrypoint: python3 -m uvicorn taigaishida.taiga:app --port ${PORT}
env_variables:
  STORAGE_URL: "https://storage.googleapis.com/taiga-ishida-public/website-images/"
