runtime: nodejs20
env: standard

handlers:
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|txt|json|map|woff2?))$
    static_files: build/\1
    upload: build/.*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|txt|json|map|woff2?)$
    secure: always
    http_headers:
      Cache-Control: public, max-age=31536000, immutable

  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Cache-Control: public, max-age=300

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Cache-Control: public, max-age=300

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""
