runtime: nodejs20
env: standard
instance_class: F1

entrypoint: node build/index.js

automatic_scaling:
  max_instances: 2
  min_instances: 0
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""
