steps:
  # Install dependencies
  - name: "node:20"
    entrypoint: bash
    args: ["-c", "corepack enable && pnpm install --frozen-lockfile"]

  # Build the SvelteKit app
  - name: "node:20"
    entrypoint: bash
    args: ["-c", "corepack enable && pnpm run build"]

  # Deploy to App Engine (replacing existing deployment)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet", "--promote", "--stop-previous-version"]

# Set timeout for build
timeout: "1200s"
