steps:
  - name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        npm i -g pnpm
        pnpm install --frozen-lockfile
        pnpm run build

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ["app", "deploy", "app.yaml", "--quiet"]
