steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: bash
    args: ['-c', 'corepack enable && pnpm install --frozen-lockfile']
    dir: 'port2'

  # Build the SvelteKit app
  - name: 'node:20'
    entrypoint: bash
    args: ['-c', 'corepack enable && pnpm run build']
    dir: 'port2'

  # Deploy to App Engine (replacing existing deployment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', '--quiet', '--promote']
    dir: 'port2'

# Set timeout for build
timeout: '1200s'
